### ISSUE TITLE
No Longer shows 7TV emotes

### ISSUE THREAD

**Issue by BlueEyesWhiteBoomer** [teklynk/twitch_chat_emotes#2]
My guess is they changed their API or the credentials are wrong now. Any idea when that can be updated?

**Comment by teklynk** [comment]
Hello,

Sorry for the delay. 

I have updated the 7tv api to v3. This seems to have resolved the issue. Please test to verify that everything is working as expected.

**Comment by BlueEyesWhiteBoomer** [comment]
Thanks, I appreciate it. It does work now

**Comment by BlueEyesWhiteBoomer** [comment]
The same issue is happening again, its probably an annual thing?

**Comment by teklynk** [comment]
@BlueEyesWhiteBoomer 

I did some testing and got intermiten results. I also notices that the 7tv website has this message: "Under construction Some features might be unavailable" which may explain things. Thier API also apears to be in limbo. Maybe they are working on a new API? There is very little documentation on thier current API. I don't know if they have a rate-limit, require special headers with the api request.

**Comment by BlueEyesWhiteBoomer** [comment]
If there API is in limbo I get it. Thanks for checking! Not a big deal, but figured I should speak up :)
